### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGames#180] opened 2016-08-25 06:17 UTC
### Issue description

`Warning: file_put_contents(/arenas.json): failed to open stream: Permission denied in phar:///home/epicsteve33/Desktop/kcmcpe-servers/play.kcmcpe.net/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208`

<hr>

I do not know why I am getting this issue, the error does not appear until I walk around.
Also I check the permission on the sg folder and it is set to read and write the area.json file is also set to the same permission, I have no issue with any other plugin just this

### Steps to reproduce the issue
<hr>

1. Install plugin on Genisys
2. Player walks around

### OS and versions

<hr>
* Version: v0.0.2
* PHP: php7
* OS: Linux

### Crashdump, backtrace or other files

<hr>
![screenshot_2016-08-24_23-13-15](https://cloud.githubusercontent.com/assets/12077835/17958714/a4a5f2f2-6a50-11e6-91a8-c39890ef1c9e.png)

**Comment by ImagicalGamer** [comment] 2016-08-25 13:59
Confirmed issue, make sure the `SurvivalGames` file has a permission level of `777`

**Comment by ImagicalGamer** [comment] 2016-08-25 14:04
@remotevase?

**Comment by ImagicalGamer** [comment] 2016-08-25 14:12
So I tested this on a Linux Ubuntu server and when the config files are created it gives them a permission level of `776` meaning the server cannot write to the file, when I change that an the server restarts it goes back to the default permission level `776`

**Comment by remotevase** [comment] 2016-08-25 14:48
Hmm... I'll look into it...

**Comment by remotevase** [comment] 2016-08-25 14:54
chmod("/arenas.json",0778);

This should be at the beginning of our code: the first thing in the onEnable AND onLoad sections. This change permission level of file to 778

**Comment by ImagicalGamer** [comment] 2016-08-25 14:56
@remotevase I just checked into it some as well, when the file is first created it has `778` permission level but when it's created again ec) in another class the file permissions change

**Comment by remotevase** [comment] 2016-08-25 14:58
@ImagicalGamer add that code as MANY TIMES AS NEEDED so that whenever the server is running, the permissions are at ___ level. Maybe put it into a loop so every second that a player is on the server, it runs this? Maybe?

**Comment by ImagicalGamer** [comment] 2016-08-25 15:14
@remotevase That would cause some lag but we could run it on the gametask since that executes every 1.5 seconds

**Comment by remotevase** [comment] 2016-08-25 15:43
@ImagicalGamer yeah sounds good! I think im gonna add that now

**Comment by remotevase** [comment] 2016-08-25 15:46
@ImagicalGamer the highest permission level is 777 which is write for everybody, so the code would be
``` php
chmod("/arenas.json",0777);
```

**Comment by remotevase** [comment] 2016-08-25 15:48
@ImagicalGamer never mind, IDK where the GameTask is. U add it there. I will add it to onEnable and onLoad

**Comment by ImagicalGamer** [comment] 2016-08-25 19:41
ImagicalGamer\SurvivalGames\Tasks\GameTask.php

**Comment by ImagicalGamer** [comment] 2016-08-25 19:42
@remotevase `chmod($this->getDataFolder() . "/arenas.json", 0777);`

**Comment by remotevase** [comment] 2016-08-25 21:16
yeah, sounds correct...

**Comment by GlitchPlayer** [comment] 2016-08-27 07:28
Not just on Linux. It happens on Windows

**Comment by ImagicalGamer** [comment] 2016-09-12 21:13
Can we confirm that this issue is resolved?

**Comment by remotevase** [comment] 2016-09-12 21:16
It works onwindows for me, idk about linux

**Comment by ImagicalGamer** [comment] 2016-09-12 21:20
If it's fixed on Windows it should work on Linux

**Comment by ImagicalGamer** [comment] 2016-09-15 15:33
I googled it and it's probs a parent directory perm problem, so the SurvivalGames file maybe? I tried chmod on it but it still reverts back to default perms.

**Comment by EpicSteve33** [comment] 2016-09-20 18:46
@ImagicalGamer sorry for being inactive lately I will find out if the bug still happens in a few minutes

**Comment by ImagicalGamer** [comment] 2016-09-20 23:14
@EpicSteve33 It's cool :)

**Comment by EpicSteve33** [comment] 2016-09-21 21:16
@ImagicalGamer I might start contributing to sg soon I've just been so busy with school I don't have much time but I could make time in the next few days

**Comment by remotevase** [comment] 2016-09-22 01:34
@EpicSteve33 what?! You can "make time"? AMAZING!!! HOW DO YOU DO IT?!?!?!

**Comment by EpicSteve33** [comment] 2016-09-22 22:44
@remotevase well right now I have a lot of homework to do so if I get that done I will have tons of time over the weekend to work on things

**Comment by Taki21** [comment] 2016-09-22 23:04
7th grade... ugh all the pressure xD

**Comment by remotevase** [comment] 2016-09-23 01:48
@Taki21 8th grade is easier than 7th grade (so far)

**Comment by Taki21** [comment] 2016-09-23 02:35
The Teachers say:
`7th Grade is the most important year...
SO DO GOOD BRATZ`
lol

**Comment by EpicSteve33** [comment] 2016-09-23 08:29
I’m in 11th grade rn believe me it is not easy

**Comment by remotevase** [comment] 2016-09-23 10:51
@taki21 it's the most important year in my middle school. I'm in 8th grade. I have less homework than 7th grade, and this year seeems less important than grade 7.  My middle school is 5,6,7,8 grade...

**Comment by remotevase** [comment] 2016-09-23 10:52
I think high school is harder than all of middle school combined. That is my prediction

**Comment by Taki21** [comment] 2016-09-23 18:56
i predict no. In here... NYC... :p

**Comment by Taki21** [comment] 2016-09-23 18:56
wait 5th is middle school? wow... thats kewl!

**Comment by Taki21** [comment] 2016-09-23 18:57
man its the birth date that effects everyones grade xD like some one couldve been in like 9th instead their 8th cause of the birth day xD

**Comment by Taki21** [comment] 2016-09-23 18:57
And people born on December 31st are so damn lucky xD

**Comment by Taki21** [comment] 2016-09-23 18:57
1 day later Kabooom, one extra year lol

**Comment by Taki21** [comment] 2016-09-23 18:58
School is easy as long the #TEACHERS ARE GEWD! (good) TO US

**Comment by remotevase** [comment] 2016-09-23 19:44
Lol... Btw don't forget I'm in new York as well

**Comment by EpicSteve33** [comment] 2016-09-26 00:10
Whenever the server starts this happens 

```
Warning: chmod(): No such file or directory in myzip:///home/epicsteve33/Desktop/kcmcpe-servers/dev/plugins/SurvivalGames-master.zip#SurvivalGames-master/src/ImagicalGamer/SurvivalGames/Main.php on line 43

Warning: chmod(): No such file or directory in myzip:///home/epicsteve33/Desktop/kcmcpe-servers/dev/plugins/SurvivalGames-master.zip#SurvivalGames-master/src/ImagicalGamer/SurvivalGames/Main.php on line 47

Warning: chmod(): No such file or directory in myzip:///home/epicsteve33/Desktop/kcmcpe-servers/dev/plugins/SurvivalGames-master.zip#SurvivalGames-master/src/ImagicalGamer/SurvivalGames/Main.php on line 50

```

**Comment by EpicSteve33** [comment] 2016-09-27 07:24
@ImagicalGamer I found this code in a plugin maybe it could help lol
 `@mkdir($this->getDataFolder(), 0777, true);`

**Comment by remotevase** [comment] 2016-09-27 21:10
@EpicSteve33 we have to do that (currently we tried to fix with chmod but didnt work...) but instead of 755, should set to 777

**Comment by ImagicalGamer** [comment] 2016-09-28 14:03
This is getting utterly ridiculous, we either need to locate the source of the issue or rewrite the entire plugin. This is the only plugin I'm having issues with, so it's something were doing.

**Closed** 2016-09-28 14:17 UTC
Labels: Confirmed, Critical Bug, Fixed? Apparently not!, Important!

**Comment by remotevase** [comment] 2016-09-28 15:50
did that fix it?

**Comment by ImagicalGamer** [comment] 2016-09-28 16:14
Yes it was a class mistake that caused all of that.

**Comment by EpicSteve33** [comment] 2016-09-29 08:43
@ImagicalGamer Not completely fixed when a player clicks on a sign this error gets spammed 

`Warning: file_put_contents(/config.yml): failed to open stream: Permission denied in /home/epicsteve33/Desktop/kcmcpe-servers/dev/src/pocketmine/utils/Config.php on line 207`

Also Players get put in void and dies
